package ibmtest.kjerauld.washington.edu.ibmtest

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import android.webkit.WebSettings
import android.webkit.WebView

class PersonalityValues : AppCompatActivity() {

    private lateinit var wv : WebView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.tone_chart)

        wv = findViewById(R.id.web)

        val data = intent.extras.getSerializable("data") as HashMap<String, ArrayList<Double>>

        var values : String = ""

        //println(data.keys)
        val keys : ArrayList<String> = ArrayList(data.keys)

        for (a in 0..keys.size - 1){
            val name : String = keys[a]
            val items : ArrayList<Double>? = data.get(name)

            val percentile : Double = items!![0]
            val raw : Double = items[1]
            values += "['" + name + "', " + percentile + ", " + raw + "],"
        }

        println(values)

        val chart = "<html>\n" +
                "  <head>\n" +
                "    <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n" +
                "    <script type=\"text/javascript\">\n" +
                "      google.charts.load('current', {'packages':['bar']});\n" +
                "      google.charts.setOnLoadCallback(drawChart);\n" +
                "\n" +
                "      function drawChart() {\n" +
                "        var data = google.visualization.arrayToDataTable([\n" +
                "          ['Personality Value', 'Percentile', 'Overall Score']," + values +
                "        ]);\n" +
                "\n" +
                "        var options = {\n" +
                "          chart: {\n" +
                "            title: 'Predicted Personality Values',\n" +
                "            subtitle: 'Values Generated by IBM Watson From Chat Analysis',\n" +
                "          },\n" +
                "          bars: 'horizontal' // Required for Material Bar Charts.\n" +
                "        };\n" +
                "\n" +
                "        var chart = new google.charts.Bar(document.getElementById('barchart_material'));\n" +
                "\n" +
                "        chart.draw(data, google.charts.Bar.convertOptions(options));\n" +
                "      }\n" +
                "    </script>\n" +
                "  </head>\n" +
                "  <body>\n" +
                "    <div id=\"barchart_material\" style=\"width: 900px; height: 500px;\"></div>\n" +
                "  </body>\n" +
                "</html>"

        val settings : WebSettings = wv.settings
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = true
        settings.loadWithOverviewMode = true
        settings.useWideViewPort = true
        settings.builtInZoomControls = true

        wv.loadDataWithBaseURL("file:///android_asset/", chart, "text/html", "utf-8", null )
    }
}
